server:
  port: 8170
  servlet:
    context-path: /web-market-analytics
utils:
  product:
    prefix: SPRING_WEB_APP_ANALYTICS
#integrations:
#  core-service:
#    url: http://localhost:5555/core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:analyticsDB;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  core-service:
    url: http://localhost:5555/core